import type { AttackGraph, GraphFinding, GraphNode } from "./graph.js";

export function renderGraphMarkdown(graph: AttackGraph): string {
  const lines: string[] = [];
  const { summary, stats, findings, nodes } = graph;

  lines.push("# KubeTrail Analysis Report\n");

  // Summary
  lines.push("## Target Context\n");
  lines.push(`| Field | Value |`);
  lines.push(`|-------|-------|`);
  if (summary.podName) lines.push(`| Pod | \`${summary.podName}\` |`);
  if (summary.namespace) lines.push(`| Namespace | \`${summary.namespace}\` |`);
  if (summary.apiServer) lines.push(`| API Server | \`${summary.apiServer}\` |`);
  if (summary.mode) lines.push(`| Mode | ${summary.mode} |`);
  lines.push(`| Facts | ${summary.factCount} |`);
  lines.push(`| Collectors | ${summary.collectorCount} |`);
  if (summary.errorCount > 0) lines.push(`| Errors | ${summary.errorCount} |`);
  lines.push("");

  // Stats
  if (Object.keys(stats).length > 0) {
    lines.push("## Stats\n");
    for (const [key, val] of Object.entries(stats)) {
      if (val > 0) lines.push(`- **${key}**: ${val}`);
    }
    lines.push("");
  }

  // Findings
  if (findings.length > 0) {
    lines.push("## Findings\n");
    const grouped = groupBy(findings, (f) => f.category);
    for (const cat of ["lpe", "escape", "exploit", "material", "blocked", "context"] as const) {
      const items = grouped.get(cat);
      if (!items || items.length === 0) continue;
      lines.push(`### ${categoryLabel(cat)} (${items.length})\n`);
      for (const f of items) {
        lines.push(`#### ${severityBadge(f.severity)} ${f.title}\n`);
        if (f.description) lines.push(`${f.description}\n`);
        if (f.evidence.length > 0) {
          lines.push(`**Evidence**: ${f.evidence.map((e) => `\`${e}\``).join(", ")}\n`);
        }
        if (f.templates.length > 0) {
          lines.push(`**EXP Templates**: ${f.templates.map((t) => `\`${t}\``).join(", ")}\n`);
        }
        if (f.nextSteps.length > 0) {
          lines.push("**Next Steps**:\n");
          for (const s of f.nextSteps) lines.push(`- ${s}`);
          lines.push("");
        }
      }
    }
  }

  // Nodes
  if (nodes.length > 0) {
    lines.push("## Attack Surface Nodes\n");
    const byType = groupBy(nodes, (n) => n.type);
    for (const [type, items] of byType) {
      lines.push(`### ${type} (${items.length})\n`);
      for (const n of items) {
        const risk = n.risk !== "info" && n.risk !== "unknown" ? ` [${n.risk}]` : "";
        lines.push(`- \`${n.label}\`${risk}${n.subtitle ? " — " + n.subtitle : ""}`);
      }
      lines.push("");
    }
  }

  lines.push("---\n");
  lines.push(`*Generated by KubeTrail Desktop — ${new Date().toISOString()}*\n`);

  return lines.join("\n");
}

function categoryLabel(cat: string): string {
  const labels: Record<string, string> = {
    escape: "Escape Paths",
    exploit: "Exploitable Permissions",
    lpe: "Linux Local Privilege Escalation",
    material: "Sensitive Material",
    blocked: "Blocked (Mitigated)",
    context: "Context",
  };
  return labels[cat] ?? cat;
}

function severityBadge(sev: string): string {
  const badges: Record<string, string> = {
    critical: "[CRITICAL]",
    high: "[HIGH]",
    medium: "[MEDIUM]",
    low: "[LOW]",
    info: "[INFO]",
    blocked: "[BLOCKED]",
  };
  return badges[sev] ?? `[${sev.toUpperCase()}]`;
}

function groupBy<T>(items: T[], key: (item: T) => string): Map<string, T[]> {
  const map = new Map<string, T[]>();
  for (const item of items) {
    const k = key(item);
    const arr = map.get(k);
    if (arr) arr.push(item);
    else map.set(k, [item]);
  }
  return map;
}
