// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agentmgr} from '../models';
import {kube} from '../models';
import {main} from '../models';
import {json} from '../models';
import {scanner} from '../models';
import {store} from '../models';

export function AgentLogs():Promise<Array<string>>;

export function CheckAgentRuntime(arg1:agentmgr.AgentConfig):Promise<agentmgr.AgentRuntimeInfo>;

export function CheckNodeShellAccess(arg1:string,arg2:string):Promise<kube.NodeShellAccess>;

export function ClusterExtensionProxyPath(arg1:string):Promise<string>;

export function ConfigureAgent(arg1:agentmgr.AgentConfig):Promise<void>;

export function ConnectCluster(arg1:string):Promise<main.ClusterInfo>;

export function CreatePersistenceCronJob(arg1:string,arg2:kube.WorkloadCreationRequest):Promise<kube.PersistenceResult>;

export function CreatePersistenceDaemonSet(arg1:string,arg2:kube.WorkloadCreationRequest):Promise<kube.PersistenceResult>;

export function CreatePersistenceDeployment(arg1:string,arg2:kube.WorkloadCreationRequest):Promise<kube.PersistenceResult>;

export function CreatePersistenceSA(arg1:string,arg2:kube.SACreationRequest):Promise<kube.PersistenceResult>;

export function DeleteAgentSkill(arg1:string):Promise<void>;

export function DeleteCluster(arg1:string):Promise<void>;

export function DeleteNodeFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteNodeShellPod(arg1:string,arg2:string):Promise<void>;

export function DeletePersistenceResource(arg1:string,arg2:kube.PersistenceTechnique,arg3:string,arg4:string):Promise<void>;

export function DeletePodFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function DeleteScanResult(arg1:string):Promise<void>;

export function DescribePod(arg1:string,arg2:string,arg3:string):Promise<kube.PodDetail>;

export function DisconnectCluster(arg1:string):Promise<void>;

export function DownloadNodeFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DownloadPodFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function EnsureAgentRunning():Promise<void>;

export function ExportAnalysisReport(arg1:string,arg2:string):Promise<void>;

export function ExportScanResult(arg1:string):Promise<void>;

export function GenerateExp(arg1:main.GenerateExpRequest):Promise<json.RawMessage>;

export function GenerateShadowKubeconfig(arg1:string,arg2:kube.SACreationRequest):Promise<kube.KubeconfigResult>;

export function GetAgentDisplayConfig():Promise<agentmgr.AgentConfig>;

export function GetAgentRuntimeInfo():Promise<agentmgr.AgentRuntimeInfo>;

export function GetAgentSkill(arg1:string):Promise<agentmgr.AgentSkill>;

export function GetAgentStatus():Promise<agentmgr.AgentStatus>;

export function GetAttackGraph(arg1:string):Promise<json.RawMessage>;

export function GetSAKubeconfig(arg1:string,arg2:string,arg3:string):Promise<kube.KubeconfigResult>;

export function GetScanResult(arg1:string):Promise<scanner.ScanResult>;

export function ImportScanResult():Promise<scanner.ScanResult>;

export function ImportScanResultPath(arg1:string):Promise<scanner.ScanResult>;

export function InjectPullSecret(arg1:string,arg2:string):Promise<kube.PersistenceResult>;

export function ListAgentSkills():Promise<Array<agentmgr.SkillInfo>>;

export function ListClusterExtensions(arg1:main.ClusterDTO):Promise<Array<kube.ClusterExtensionInfo>>;

export function ListClusters():Promise<Array<store.ClusterEntry>>;

export function ListExpTemplates():Promise<json.RawMessage>;

export function ListNamespaces(arg1:string):Promise<Array<kube.Namespace>>;

export function ListNodeFiles(arg1:string,arg2:string,arg3:string):Promise<Array<kube.FileEntry>>;

export function ListNodes(arg1:string):Promise<Array<kube.NodeInfo>>;

export function ListPersistenceResources(arg1:string):Promise<Array<kube.PersistenceResourceInfo>>;

export function ListPodFiles(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Array<kube.FileEntry>>;

export function ListPods(arg1:string,arg2:string):Promise<Array<kube.PodInfo>>;

export function ListPortForwards():Promise<Array<main.PFInfo>>;

export function ListScanResults():Promise<Array<scanner.ScanResult>>;

export function MaterializeSensitive(arg1:string,arg2:string):Promise<json.RawMessage>;

export function OpenDirectoryPath(arg1:string):Promise<void>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenKubeconfigDialog():Promise<Record<string, string>>;

export function PersistenceCatalog():Promise<Array<main.PersistenceCatalogItem>>;

export function PickDirectory():Promise<string>;

export function PickOpenFile():Promise<string>;

export function PickSaveFile(arg1:string):Promise<string>;

export function ReadNodeFile(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function ReadPodFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<string>;

export function ReconCatalog():Promise<Array<kube.ReconPreset>>;

export function ReconRead(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function RequestSAToken(arg1:string,arg2:kube.TokenRequestParams):Promise<kube.TokenResult>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartAgent():Promise<void>;

export function SaveAgentConfigOnly(arg1:agentmgr.AgentConfig):Promise<void>;

export function SaveAgentSkill(arg1:agentmgr.SkillUpsertRequest):Promise<agentmgr.AgentSkill>;

export function SaveCluster(arg1:main.ClusterDTO):Promise<string>;

export function SaveKubeconfigFile(arg1:kube.KubeconfigResult):Promise<void>;

export function StartAgentChat(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function StartClusterScan(arg1:string,arg2:scanner.ScanOptions):Promise<string>;

export function StartLogs(arg1:main.LogStartRequest):Promise<string>;

export function StartNodeTerminal(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartPortForward(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<string>;

export function StartTerminal(arg1:main.TerminalStartRequest):Promise<string>;

export function StopAgent():Promise<void>;

export function StopAgentChat(arg1:string):Promise<boolean>;

export function StopLogs(arg1:string):Promise<boolean>;

export function StopPortForward(arg1:string):Promise<boolean>;

export function StopTerminal(arg1:string):Promise<boolean>;

export function TestAgentConnection(arg1:agentmgr.AgentConfig):Promise<string>;

export function TestConnection(arg1:main.ClusterDTO):Promise<string>;

export function UploadNodeFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UploadPodFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
