// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentLogs() {
  return window['go']['main']['App']['AgentLogs']();
}

export function CheckAgentRuntime(arg1) {
  return window['go']['main']['App']['CheckAgentRuntime'](arg1);
}

export function CheckNodeShellAccess(arg1, arg2) {
  return window['go']['main']['App']['CheckNodeShellAccess'](arg1, arg2);
}

export function ClusterExtensionProxyPath(arg1) {
  return window['go']['main']['App']['ClusterExtensionProxyPath'](arg1);
}

export function ConfigureAgent(arg1) {
  return window['go']['main']['App']['ConfigureAgent'](arg1);
}

export function ConnectCluster(arg1) {
  return window['go']['main']['App']['ConnectCluster'](arg1);
}

export function CreatePersistenceCronJob(arg1, arg2) {
  return window['go']['main']['App']['CreatePersistenceCronJob'](arg1, arg2);
}

export function CreatePersistenceDaemonSet(arg1, arg2) {
  return window['go']['main']['App']['CreatePersistenceDaemonSet'](arg1, arg2);
}

export function CreatePersistenceDeployment(arg1, arg2) {
  return window['go']['main']['App']['CreatePersistenceDeployment'](arg1, arg2);
}

export function CreatePersistenceSA(arg1, arg2) {
  return window['go']['main']['App']['CreatePersistenceSA'](arg1, arg2);
}

export function DeleteAgentSkill(arg1) {
  return window['go']['main']['App']['DeleteAgentSkill'](arg1);
}

export function DeleteCluster(arg1) {
  return window['go']['main']['App']['DeleteCluster'](arg1);
}

export function DeleteNodeFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteNodeFile'](arg1, arg2, arg3);
}

export function DeleteNodeShellPod(arg1, arg2) {
  return window['go']['main']['App']['DeleteNodeShellPod'](arg1, arg2);
}

export function DeletePersistenceResource(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeletePersistenceResource'](arg1, arg2, arg3, arg4);
}

export function DeletePodFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DeletePodFile'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteScanResult(arg1) {
  return window['go']['main']['App']['DeleteScanResult'](arg1);
}

export function DescribePod(arg1, arg2, arg3) {
  return window['go']['main']['App']['DescribePod'](arg1, arg2, arg3);
}

export function DisconnectCluster(arg1) {
  return window['go']['main']['App']['DisconnectCluster'](arg1);
}

export function DownloadNodeFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadNodeFile'](arg1, arg2, arg3, arg4);
}

export function DownloadPodFile(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['DownloadPodFile'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function EnsureAgentRunning() {
  return window['go']['main']['App']['EnsureAgentRunning']();
}

export function ExportAnalysisReport(arg1, arg2) {
  return window['go']['main']['App']['ExportAnalysisReport'](arg1, arg2);
}

export function ExportScanResult(arg1) {
  return window['go']['main']['App']['ExportScanResult'](arg1);
}

export function GenerateExp(arg1) {
  return window['go']['main']['App']['GenerateExp'](arg1);
}

export function GenerateShadowKubeconfig(arg1, arg2) {
  return window['go']['main']['App']['GenerateShadowKubeconfig'](arg1, arg2);
}

export function GetAgentDisplayConfig() {
  return window['go']['main']['App']['GetAgentDisplayConfig']();
}

export function GetAgentRuntimeInfo() {
  return window['go']['main']['App']['GetAgentRuntimeInfo']();
}

export function GetAgentSkill(arg1) {
  return window['go']['main']['App']['GetAgentSkill'](arg1);
}

export function GetAgentStatus() {
  return window['go']['main']['App']['GetAgentStatus']();
}

export function GetAttackGraph(arg1) {
  return window['go']['main']['App']['GetAttackGraph'](arg1);
}

export function GetSAKubeconfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSAKubeconfig'](arg1, arg2, arg3);
}

export function GetScanResult(arg1) {
  return window['go']['main']['App']['GetScanResult'](arg1);
}

export function ImportScanResult() {
  return window['go']['main']['App']['ImportScanResult']();
}

export function ImportScanResultPath(arg1) {
  return window['go']['main']['App']['ImportScanResultPath'](arg1);
}

export function InjectPullSecret(arg1, arg2) {
  return window['go']['main']['App']['InjectPullSecret'](arg1, arg2);
}

export function ListAgentSkills() {
  return window['go']['main']['App']['ListAgentSkills']();
}

export function ListClusterExtensions(arg1) {
  return window['go']['main']['App']['ListClusterExtensions'](arg1);
}

export function ListClusters() {
  return window['go']['main']['App']['ListClusters']();
}

export function ListExpTemplates() {
  return window['go']['main']['App']['ListExpTemplates']();
}

export function ListNamespaces(arg1) {
  return window['go']['main']['App']['ListNamespaces'](arg1);
}

export function ListNodeFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListNodeFiles'](arg1, arg2, arg3);
}

export function ListNodes(arg1) {
  return window['go']['main']['App']['ListNodes'](arg1);
}

export function ListPersistenceResources(arg1) {
  return window['go']['main']['App']['ListPersistenceResources'](arg1);
}

export function ListPodFiles(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ListPodFiles'](arg1, arg2, arg3, arg4, arg5);
}

export function ListPods(arg1, arg2) {
  return window['go']['main']['App']['ListPods'](arg1, arg2);
}

export function ListPortForwards() {
  return window['go']['main']['App']['ListPortForwards']();
}

export function ListScanResults() {
  return window['go']['main']['App']['ListScanResults']();
}

export function MaterializeSensitive(arg1, arg2) {
  return window['go']['main']['App']['MaterializeSensitive'](arg1, arg2);
}

export function OpenDirectoryPath(arg1) {
  return window['go']['main']['App']['OpenDirectoryPath'](arg1);
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function OpenKubeconfigDialog() {
  return window['go']['main']['App']['OpenKubeconfigDialog']();
}

export function PersistenceCatalog() {
  return window['go']['main']['App']['PersistenceCatalog']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickOpenFile() {
  return window['go']['main']['App']['PickOpenFile']();
}

export function PickSaveFile(arg1) {
  return window['go']['main']['App']['PickSaveFile'](arg1);
}

export function ReadNodeFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReadNodeFile'](arg1, arg2, arg3, arg4);
}

export function ReadPodFile(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ReadPodFile'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ReconCatalog() {
  return window['go']['main']['App']['ReconCatalog']();
}

export function ReconRead(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ReconRead'](arg1, arg2, arg3, arg4, arg5);
}

export function RequestSAToken(arg1, arg2) {
  return window['go']['main']['App']['RequestSAToken'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestartAgent() {
  return window['go']['main']['App']['RestartAgent']();
}

export function SaveAgentConfigOnly(arg1) {
  return window['go']['main']['App']['SaveAgentConfigOnly'](arg1);
}

export function SaveAgentSkill(arg1) {
  return window['go']['main']['App']['SaveAgentSkill'](arg1);
}

export function SaveCluster(arg1) {
  return window['go']['main']['App']['SaveCluster'](arg1);
}

export function SaveKubeconfigFile(arg1) {
  return window['go']['main']['App']['SaveKubeconfigFile'](arg1);
}

export function StartAgentChat(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartAgentChat'](arg1, arg2, arg3, arg4, arg5);
}

export function StartClusterScan(arg1, arg2) {
  return window['go']['main']['App']['StartClusterScan'](arg1, arg2);
}

export function StartLogs(arg1) {
  return window['go']['main']['App']['StartLogs'](arg1);
}

export function StartNodeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartNodeTerminal'](arg1, arg2, arg3);
}

export function StartPortForward(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartPortForward'](arg1, arg2, arg3, arg4, arg5);
}

export function StartTerminal(arg1) {
  return window['go']['main']['App']['StartTerminal'](arg1);
}

export function StopAgent() {
  return window['go']['main']['App']['StopAgent']();
}

export function StopAgentChat(arg1) {
  return window['go']['main']['App']['StopAgentChat'](arg1);
}

export function StopLogs(arg1) {
  return window['go']['main']['App']['StopLogs'](arg1);
}

export function StopPortForward(arg1) {
  return window['go']['main']['App']['StopPortForward'](arg1);
}

export function StopTerminal(arg1) {
  return window['go']['main']['App']['StopTerminal'](arg1);
}

export function TestAgentConnection(arg1) {
  return window['go']['main']['App']['TestAgentConnection'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UploadNodeFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadNodeFile'](arg1, arg2, arg3, arg4);
}

export function UploadPodFile(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UploadPodFile'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
