export type ExpKind = "generated-command" | "k8s-object" | "json-patch" | "prebuilt-binary" | "source-build";

export type ExpMode = "safe" | "full" | "dangerous";

export type ExpRunAt = "operator-workstation" | "target-pod" | "generated-bundle";

export type ExpTemplate = {
  templateId: string;
  kind: ExpKind;
  mode: ExpMode;
  runAt: ExpRunAt;
  title: string;
  summary: string;
  defaultParams?: Record<string, string | number | boolean>;
  parameterDocs?: Record<string, string>;
  preconditions: string[];
  sideEffects: string[];
  cleanup?: string[];
};

export const expTemplates: ExpTemplate[] = [
  {
    templateId: "cloud-metadata-verify",
    kind: "generated-command",
    mode: "safe",
    runAt: "target-pod",
    title: "Cloud metadata reachability verification",
    summary: "Generate read-only IMDS probes for AWS, GCP, Azure, and generic cloud metadata endpoints.",
    defaultParams: { provider: "auto", timeoutSeconds: 2, includeCredentialValues: false },
    parameterDocs: {
      provider: "auto, aws, gcp, azure, alibaba, tencent, huawei, oci, or generic",
      includeCredentialValues: "false by default; true only in an authorized local workflow",
    },
    preconditions: ["Run from the target pod network namespace or an equivalent debug shell."],
    sideEffects: ["metadata HTTP GET/PUT requests only"],
  },
  {
    templateId: "cloud-identity-verify",
    kind: "generated-command",
    mode: "safe",
    runAt: "operator-workstation",
    title: "Cloud identity read-only verification",
    summary: "Generate read-only cloud caller identity commands for authorized cloud credentials.",
    defaultParams: { provider: "aws" },
    preconditions: ["Authorized cloud CLI credentials are available in the operator environment."],
    sideEffects: ["cloud identity read-only API calls"],
  },
  {
    templateId: "serviceaccount-token-api-verify",
    kind: "generated-command",
    mode: "safe",
    runAt: "target-pod",
    title: "Mounted service account token API verification",
    summary: "Generate in-pod commands to verify the mounted token can reach Kubernetes API discovery endpoints.",
    defaultParams: { tokenPath: "/var/run/secrets/kubernetes.io/serviceaccount/token" },
    preconditions: ["Run inside the target pod or a shell with the same mounted ServiceAccount token."],
    sideEffects: ["Kubernetes API discovery GET requests only"],
  },
  {
    templateId: "secret-list-get-verify",
    kind: "generated-command",
    mode: "safe",
    runAt: "operator-workstation",
    title: "Kubernetes Secret read verification",
    summary: "Generate kubectl commands to verify secret list/get capability without printing secret data by default.",
    defaultParams: { namespace: "default", printSecretData: false },
    preconditions: ["kubectl is configured with the subject being validated."],
    sideEffects: ["Kubernetes API read requests for Secret metadata or selected Secret object"],
  },
  {
    templateId: "runtime-socket-verify",
    kind: "source-build",
    mode: "safe",
    runAt: "target-pod",
    title: "Container runtime socket verifier",
    summary: "Generate a tiny Go verifier that checks configured Unix socket paths and optionally attempts a non-mutating dial.",
    defaultParams: { socketPath: "/run/containerd/containerd.sock", binaryName: "kt-runtime-socket-verify" },
    preconditions: ["Compile on the operator workstation or inside an equivalent build container.", "Run from the target pod/container where the socket path is visible."],
    sideEffects: ["local filesystem stat and optional Unix socket dial only"],
  },
  {
    templateId: "nodes-proxy-verify",
    kind: "generated-command",
    mode: "safe",
    runAt: "operator-workstation",
    title: "Kubernetes nodes/proxy health verification",
    summary: "Generate kubectl raw API commands for node proxy health endpoints.",
    defaultParams: { node: "<node-name>" },
    preconditions: ["kubectl is configured with the subject being validated.", "The target node name is known."],
    sideEffects: ["Kubernetes API request to node proxy health endpoint"],
  },
  {
    templateId: "kubelet-api-verify",
    kind: "generated-command",
    mode: "safe",
    runAt: "operator-workstation",
    title: "Direct kubelet API reachability verification",
    summary: "Generate read-only curl probes for direct kubelet API exposure.",
    defaultParams: { kubeletUrl: "https://<node-ip>:10250", timeoutSeconds: 3 },
    preconditions: ["Operator workstation or pod can route to the kubelet endpoint."],
    sideEffects: ["kubelet health/version read requests"],
  },
  {
    templateId: "etcd-access-verify",
    kind: "generated-command",
    mode: "safe",
    runAt: "operator-workstation",
    title: "etcd endpoint reachability verification",
    summary: "Generate read-only endpoint status commands for authorized etcd access checks.",
    defaultParams: { endpoint: "https://<etcd-host>:2379" },
    preconditions: ["Authorized etcd client material is available if mTLS is required."],
    sideEffects: ["etcd endpoint status read request"],
  },
  {
    templateId: "pod-create-job",
    kind: "k8s-object",
    mode: "full",
    runAt: "operator-workstation",
    title: "Controlled Kubernetes Job creation",
    summary: "Generate a short-lived Job to verify workload creation in a namespace.",
    defaultParams: { namespace: "default", name: "kt-job-check", image: "busybox:1.36", command: "id; uname -a" },
    preconditions: ["pods/create or jobs/create is allowed in the target namespace.", "Admission allows the generated workload."],
    sideEffects: ["creates one short-lived Job and Pod"],
    cleanup: ["delete generated Job"],
  },
  {
    templateId: "pod-hostpath",
    kind: "k8s-object",
    mode: "full",
    runAt: "operator-workstation",
    title: "Controlled hostPath pod validation",
    summary: "Generate a read-only hostPath validation pod.",
    defaultParams: { namespace: "default", name: "kt-hostpath-check", image: "busybox:1.36", targetPath: "/var/run", mountPath: "/host", holdSeconds: 30 },
    preconditions: ["pods/create is allowed in the target namespace.", "Admission allows hostPath for the chosen path."],
    sideEffects: ["creates one Pod with read-only hostPath mount"],
    cleanup: ["delete generated Pod"],
  },
  {
    templateId: "pod-privileged",
    kind: "k8s-object",
    mode: "full",
    runAt: "operator-workstation",
    title: "Controlled privileged pod validation",
    summary: "Generate a short-lived privileged validation pod.",
    defaultParams: { namespace: "default", name: "kt-privileged-check", image: "busybox:1.36", holdSeconds: 30 },
    preconditions: ["pods/create is allowed in the target namespace.", "Admission allows privileged containers."],
    sideEffects: ["creates one privileged Pod"],
    cleanup: ["delete generated Pod"],
  },
  {
    templateId: "pod-hostpid",
    kind: "k8s-object",
    mode: "full",
    runAt: "operator-workstation",
    title: "Controlled hostPID pod validation",
    summary: "Generate a short-lived hostPID validation pod.",
    defaultParams: { namespace: "default", name: "kt-hostpid-check", image: "busybox:1.36", holdSeconds: 30 },
    preconditions: ["pods/create is allowed in the target namespace.", "Admission allows hostPID."],
    sideEffects: ["creates one Pod with hostPID=true"],
    cleanup: ["delete generated Pod"],
  },
  {
    templateId: "pod-hostnetwork",
    kind: "k8s-object",
    mode: "full",
    runAt: "operator-workstation",
    title: "Controlled hostNetwork pod validation",
    summary: "Generate a short-lived hostNetwork validation pod.",
    defaultParams: { namespace: "default", name: "kt-hostnetwork-check", image: "busybox:1.36", holdSeconds: 30 },
    preconditions: ["pods/create is allowed in the target namespace.", "Admission allows hostNetwork."],
    sideEffects: ["creates one Pod with hostNetwork=true"],
    cleanup: ["delete generated Pod"],
  },
  {
    templateId: "ephemeralcontainers-patch",
    kind: "json-patch",
    mode: "full",
    runAt: "operator-workstation",
    title: "Ephemeral container patch validation",
    summary: "Generate JSON patch artifacts for an ephemeral container validation.",
    defaultParams: { namespace: "default", pod: "<target-pod>", containerName: "kt-debug", image: "busybox:1.36" },
    preconditions: ["pods/ephemeralcontainers patch or update is allowed.", "Target Pod exists and admission allows the debug image."],
    sideEffects: ["patches target Pod spec to add an ephemeral container"],
  },
  {
    templateId: "pods-exec-verify",
    kind: "generated-command",
    mode: "safe",
    runAt: "operator-workstation",
    title: "pods/exec capability verification",
    summary: "Generate kubectl exec command for a benign identity check in a selected container.",
    defaultParams: { namespace: "default", pod: "<target-pod>", container: "", command: "id" },
    preconditions: ["pods/exec create is allowed for the target Pod."],
    sideEffects: ["execs a read-only command in the selected container"],
  },
  {
    templateId: "impersonate-verify",
    kind: "generated-command",
    mode: "safe",
    runAt: "operator-workstation",
    title: "Kubernetes impersonation verification",
    summary: "Generate kubectl auth checks for a target impersonation subject.",
    defaultParams: { as: "system:serviceaccount:default:default", verb: "get", resource: "pods", namespace: "default" },
    preconditions: ["impersonate permission may be present for the selected subject."],
    sideEffects: ["Kubernetes authorization review request"],
  },
  {
    templateId: "rbac-bind-escalate-verify",
    kind: "generated-command",
    mode: "safe",
    runAt: "operator-workstation",
    title: "RBAC bind/escalate preflight verification",
    summary: "Generate kubectl auth checks for RBAC bind/escalate primitives without creating bindings.",
    defaultParams: { namespace: "default" },
    preconditions: ["kubectl is configured with the subject being validated."],
    sideEffects: ["Kubernetes authorization review requests"],
  },
  {
    templateId: "serviceaccount-rbac-persistence",
    kind: "k8s-object",
    mode: "full",
    runAt: "operator-workstation",
    title: "Scoped ServiceAccount RBAC persistence",
    summary: "Generate ServiceAccount, Role or ClusterRole, binding, and optional long-lived token Secret for scoped persistence validation.",
    defaultParams: {
      namespace: "default",
      name: "kt-scoped-sa",
      scope: "namespace",
      preset: "secret-read",
      createLongLivedToken: false,
    },
    parameterDocs: {
      scope: "namespace or cluster",
      preset: "secret-read, exec, workload-patch, token-request, namespace-admin, or cluster-admin",
      createLongLivedToken: "false by default; true creates a kubernetes.io/service-account-token Secret",
    },
    preconditions: [
      "Authorized operator has create permission for serviceaccounts and the selected RBAC resources.",
      "Use cluster scope only when ClusterRole and ClusterRoleBinding creation is authorized.",
    ],
    sideEffects: ["creates Kubernetes identity and RBAC resources", "optionally creates a long-lived ServiceAccount token Secret"],
    cleanup: ["delete generated ServiceAccount, RBAC binding, role, and token Secret"],
  },
  {
    templateId: "csr-client-cert-persistence",
    kind: "generated-command",
    mode: "dangerous",
    runAt: "operator-workstation",
    title: "CSR client certificate persistence",
    summary: "Generate a script that creates a Kubernetes client certificate signing request and builds a kubeconfig from the issued certificate.",
    defaultParams: {
      username: "kubetrail-audit",
      groups: "system:authenticated",
      csrName: "kt-client-cert",
      signerName: "kubernetes.io/kube-apiserver-client",
      expirationSeconds: 86400,
      autoApprove: false,
      outputPrefix: "kt-client-cert",
    },
    parameterDocs: {
      groups: "comma-separated X.509 organization values",
      autoApprove: "true only when CSR approval is explicitly authorized",
    },
    preconditions: [
      "kubectl is configured with the subject being validated.",
      "openssl is installed on the operator workstation.",
      "The subject can create/get CertificateSigningRequests; autoApprove additionally needs approval and signer approve permissions.",
    ],
    sideEffects: ["creates a CertificateSigningRequest", "may approve and issue a client certificate", "writes local key, csr, certificate, and kubeconfig files"],
    cleanup: ["delete generated CertificateSigningRequest", "remove generated local key, csr, cert, and kubeconfig files"],
  },
  {
    templateId: "workload-patch-sidecar-persistence",
    kind: "json-patch",
    mode: "dangerous",
    runAt: "operator-workstation",
    title: "Existing workload sidecar patch persistence",
    summary: "Generate JSON patch artifacts that add a controlled sidecar to an existing Deployment, DaemonSet, or StatefulSet template.",
    defaultParams: {
      namespace: "default",
      workloadKind: "deployment",
      workloadName: "<target-workload>",
      containerName: "kt-sidecar",
      image: "busybox:1.36",
      command: "while true; do sleep 3600; done",
    },
    preconditions: [
      "patch/update is allowed for the selected workload controller.",
      "Admission allows the sidecar image and resulting PodSpec.",
      "The operator has change approval for the selected workload.",
    ],
    sideEffects: ["patches an existing workload template", "triggers rollout or DaemonSet reconciliation", "creates or restarts Pods depending on controller behavior"],
    cleanup: ["run the generated cleanup.sh to remove the added sidecar container by name"],
  },
  {
    templateId: "pull-secret-injection",
    kind: "generated-command",
    mode: "full",
    runAt: "operator-workstation",
    title: "ImagePullSecret ServiceAccount injection",
    summary: "Generate commands to create a dockerconfigjson Secret and patch a ServiceAccount imagePullSecrets list.",
    defaultParams: {
      namespace: "default",
      serviceAccount: "default",
      secretName: "kt-pull-secret",
      dockerConfigJsonPath: "",
    },
    parameterDocs: {
      dockerConfigJsonPath: "optional path to a reviewed .dockerconfigjson file; empty creates a placeholder auths object",
    },
    preconditions: [
      "create secrets and patch serviceaccounts are allowed in the namespace.",
      "Registry credential material is approved for use in this assessment if dockerConfigJsonPath is set.",
    ],
    sideEffects: ["creates or updates a Secret", "patches imagePullSecrets on the selected ServiceAccount"],
    cleanup: ["remove the generated imagePullSecret reference from the ServiceAccount", "delete the generated Secret"],
  },
  {
    templateId: "admission-persistence-review",
    kind: "generated-command",
    mode: "safe",
    runAt: "operator-workstation",
    title: "Admission persistence surface review",
    summary: "Generate read-only commands for webhook, CEL admission policy, and namespace selector surfaces that can inject or preserve access.",
    defaultParams: { namespace: "all" },
    preconditions: ["kubectl is configured for the authorized assessment context."],
    sideEffects: ["Kubernetes API read requests only"],
  },
  {
    templateId: "static-pod-node-persistence-review",
    kind: "generated-command",
    mode: "safe",
    runAt: "target-pod",
    title: "Static pod and node manifest persistence review",
    summary: "Generate read-only node-side commands to inspect common kubelet static pod manifest locations and permissions.",
    defaultParams: { includeFileListing: true },
    preconditions: ["Run from an authorized node shell or pod with the relevant host filesystem paths mounted read-only."],
    sideEffects: ["local filesystem stat/list requests only"],
  },
  {
    templateId: "registry-auth-verify",
    kind: "generated-command",
    mode: "safe",
    runAt: "operator-workstation",
    title: "Registry authentication verification",
    summary: "Generate non-mutating registry manifest/auth inspection commands.",
    defaultParams: { image: "<registry>/<repo>:<tag>" },
    preconditions: ["Authorized registry credentials are present in the operator environment."],
    sideEffects: ["registry read requests"],
  },
  {
    templateId: "cve-2021-4034-pwnkit",
    kind: "prebuilt-binary",
    mode: "dangerous",
    runAt: "generated-bundle",
    title: "CVE-2021-4034 PwnKit pkexec",
    summary: "Package a reviewed ly4k/PwnKit linux-amd64 PoC binary plus pinned source and rebuild script for authorized local privilege escalation validation.",
    defaultParams: {
      pocId: "cve-2021-4034-pwnkit",
      os: "linux",
      arch: "amd64",
      binaryName: "kt-pkexec-lpe",
      variantSeed: "kubetrail-pwnkit-1923ad7b-20260609-a",
    },
    parameterDocs: {
      variantSeed: "Harmless marker embedded when rebuilding from source to produce a traceable binary hash variant.",
    },
    preconditions: [
      "Use only in an explicitly authorized lab, VM snapshot, or red-team target.",
      "Target must be Linux x86_64 with a vulnerable polkit/policykit pkexec build.",
      "Run as an unprivileged local user where /usr/bin/pkexec is present and setuid-root.",
      "Confirm vendor backport status before treating a version-only match as exploitable.",
    ],
    sideEffects: [
      "Executes a local privilege escalation PoC and may spawn a root shell or run a root command.",
      "Creates short-lived gconv/pkexec working files in the current directory while running.",
    ],
    cleanup: ["Remove the generated bundle directory from the target after validation.", "Restore the VM snapshot after successful exploitation."],
  },
  {
    templateId: "external-cve-poc",
    kind: "prebuilt-binary",
    mode: "dangerous",
    runAt: "generated-bundle",
    title: "External CVE PoC wrapper",
    summary: "Reference a pre-reviewed, pinned external PoC binary already staged under exp/assets/bin.",
    defaultParams: { pocId: "<cve-or-tool-id>", os: "linux", arch: "amd64", binaryName: "poc" },
    preconditions: ["PoC source, commit, and binary hash have been reviewed and pinned.", "Target version is confirmed vulnerable."],
    sideEffects: ["depends on the referenced PoC; inspect manifest before use"],
  },
  ...genericReviewTemplates(),
];

const publicExpTemplateIds = [
  "cloud-metadata-verify",
  "cloud-identity-verify",
  "serviceaccount-token-api-verify",
  "secret-list-get-verify",
  "runtime-socket-verify",
  "nodes-proxy-verify",
  "kubelet-api-verify",
  "etcd-access-verify",
  "pod-create-job",
  "pod-hostpath",
  "pod-privileged",
  "pod-hostpid",
  "pod-hostnetwork",
  "ephemeralcontainers-patch",
  "pods-exec-verify",
  "impersonate-verify",
  "rbac-bind-escalate-verify",
  "serviceaccount-rbac-persistence",
  "csr-client-cert-persistence",
  "workload-patch-sidecar-persistence",
  "pull-secret-injection",
  "admission-persistence-review",
  "static-pod-node-persistence-review",
  "registry-auth-verify",
  "admission-policy-review",
  "controller-persistence-review",
  "image-supply-chain-review",
  "management-interface-review",
  "network-lateral-movement-review",
  "observability-evasion-review",
  "operator-crd-abuse-review",
  "resource-hijack-dos-review",
  "secret-material-review",
  "service-ingress-exposure-review",
  "static-pod-manifest-review",
  "windows-container-review",
  "workload-rce-posture-review",
  "cve-2021-4034-pwnkit",
  "external-cve-poc",
] as const;

export const expTemplateIds = [...publicExpTemplateIds];

export function listExpTemplates(): ExpTemplate[] {
  return expTemplates.filter((template) => publicExpTemplateIds.includes(template.templateId as (typeof publicExpTemplateIds)[number]));
}

export function getExpTemplate(templateId: string): ExpTemplate | undefined {
  return expTemplates.find((template) => template.templateId === templateId);
}

function genericReviewTemplates(): ExpTemplate[] {
  const values: Array<[string, string, string]> = [
    ["admission-policy-review", "Admission policy review", "Generate read-only kubectl commands for Pod Security Admission, webhooks, and policy engines."],
    ["controller-persistence-review", "Controller persistence review", "Generate read-only kubectl commands for Deployments, DaemonSets, Jobs, CronJobs, and static-pod hints."],
    ["image-supply-chain-review", "Image supply-chain review", "Generate read-only inventory commands for images, registries, pull secrets, and mutable tags."],
    ["management-interface-review", "Management interface review", "Generate read-only discovery commands for dashboard/admin workloads and their exposure."],
    ["network-lateral-movement-review", "Network lateral movement review", "Generate read-only discovery commands for NetworkPolicies, services, endpoints, and sensitive egress paths."],
    ["observability-evasion-review", "Observability and evasion review", "Generate read-only discovery commands for audit, logs, events, and runtime security agents."],
    ["operator-crd-abuse-review", "Operator and CRD abuse review", "Generate read-only discovery commands for CRDs, operators, controller RBAC, and cross-namespace references."],
    ["resource-hijack-dos-review", "Resource hijack and DoS review", "Generate read-only discovery commands for quotas, limits, autoscaling, and resource-heavy workloads."],
    ["secret-material-review", "Secret material review", "Generate read-only commands for Secret references, mounted tokens, kubeconfigs, and registry auth metadata."],
    ["service-ingress-exposure-review", "Service and ingress exposure review", "Generate read-only discovery commands for Services, Ingresses, Gateways, NodePorts, and public routes."],
    ["static-pod-manifest-review", "Static pod manifest review", "Generate read-only commands to inspect static pod manifest paths when node access is authorized."],
    ["windows-container-review", "Windows container surface review", "Generate read-only discovery commands for Windows nodes, HostProcess pods, and Windows workloads."],
    ["workload-rce-posture-review", "Public workload RCE posture review", "Generate read-only commands to inventory exposed workloads and their post-compromise blast radius."],
  ];
  return values.map(([templateId, title, summary]) => ({
    templateId,
    kind: "generated-command" as const,
    mode: "safe" as const,
    runAt: "operator-workstation" as const,
    title,
    summary,
    defaultParams: { namespace: "all" },
    preconditions: ["kubectl is configured for the authorized assessment context."],
    sideEffects: ["Kubernetes API read requests only"],
  }));
}
